version: '3.3'
services:
  mysql:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: bkya  
    ports:
      - '3306:3306'
    expose:
      - '3306'
  mongodb_container:
    image: mongo:latest
    ports:
      - '27017:27017'
    expose:
      - '27017'  
